// @flow
const ADD_AMOUNT: 'ADD_AMOUNT' = 'ADD_AMOUNT';
const ADD_ITEM: 'ADD_ITEM' = 'ADD_ITEM';
const DELETE_ITEM: 'DELETE_ITEM' = 'DELETE_ITEM';
const RECEIVED_ITEM: 'RECEIVED_ITEM' = 'RECEIVED_ITEM';
const REMOVE_AMOUNT: 'REMOVE_AMOUNT' = 'REMOVE_AMOUNT';

export const CART_EVENTS = {
	ADD_AMOUNT,
	ADD_ITEM,
	DELETE_ITEM,
	RECEIVED_ITEM,
	REMOVE_AMOUNT
};
