// @flow
const ITEMS_FILTER_INGREDIENTS = 'ITEMS_FILTER_INGREDIENTS';
const ITEMS_FILTER_STICKERS = 'ITEMS_FILTER_STICKERS';
const ITEMS_FILTER_REMOVE = 'ITEMS_FILTER_REMOVE';

const ITEMS_SEARCH = 'ITEMS_SEARCH';

const ITEMS_RECEIVED = 'ITEMS_RECEIVED';

export const ITEMS_EVENTS = {
	ITEMS_RECEIVED
};

export const ITEMS_FILTER_EVENTS = {
	ITEMS_FILTER_INGREDIENTS,
	ITEMS_FILTER_STICKERS,
	ITEMS_FILTER_REMOVE,
	ITEMS_SEARCH
};
